-- Minimal login-less seed. This is sample data only; app-created data is stored separately by normal CRUD operations.
insert into public.companies (id,name) values ('company-omega','オメガテクノ') on conflict (id) do update set name=excluded.name;
insert into public.workplaces (id,company_id,name,address) values ('wp-1','company-omega','東京事業所','東京都千代田区'),('wp-2','company-omega','横浜事業所','神奈川県横浜市') on conflict (id) do update set name=excluded.name,address=excluded.address;
insert into public.profiles (id,company_id,workplace_id,name,role,staff_role,phone,note) values
('admin-1','company-omega','wp-1','管理者 太郎','admin','leader','090-0000-0001',null),('staff-1','company-omega','wp-1','佐藤 リーダー','staff','leader','090-0000-0002',null),('staff-2','company-omega','wp-1','鈴木 スタッフ','staff','staff','090-0000-0003',null),('staff-3','company-omega','wp-2','高橋 リーダー','staff','leader','090-0000-0004',null) on conflict (id) do update set name=excluded.name, workplace_id=excluded.workplace_id, staff_role=excluded.staff_role, phone=excluded.phone;
insert into public.availability_periods (id,company_id,period_type,target_month,week_start_date,week_end_date,deadline,status) values ('period-month-2026-07','company-omega','monthly','2026-07',null,null,'2026-06-25 23:59:00+09','open'),('period-week-2026-06-22','company-omega','weekly',null,'2026-06-22','2026-06-28','2026-06-20 23:59:00+09','open') on conflict (id) do nothing;
insert into public.project_templates (id,company_id,workplace_id,template_name,title,start_time,end_time,location,required_people,required_leaders,note,weekdays) values ('template-1','company-omega','wp-1','平日倉庫フルタイム','倉庫ピッキング','09:00','17:00','東京倉庫',5,1,'毎週 月・水・金の定番案件',array[1,3,5]) on conflict (id) do nothing;
insert into public.projects (id,company_id,workplace_id,title,project_type,work_date,start_time,end_time,location,required_people,required_leaders,note) values ('project-1','company-omega','wp-1','倉庫棚卸サポート','single','2026-06-14','09:00','17:00','東京倉庫',3,1,'勤務可能日照合デモ'),('project-2','company-omega','wp-2','夜間搬入作業','single','2026-06-16','16:00','22:00','横浜センター',2,1,''),('project-4','company-omega','wp-1','商業施設キャンペーン運営','recurring','2026-06-18','10:00','18:00','新宿モール',4,1,'継続案件デモ') on conflict (id) do nothing;
insert into public.project_days (id,project_id,work_date,start_time,end_time,required_people,required_leaders,note) values ('project-1','project-1','2026-06-14','09:00','17:00',3,1,'勤務可能日照合デモ'),('project-2','project-2','2026-06-16','16:00','22:00',2,1,''),('project-day-4-1','project-4','2026-06-18','10:00','18:00',4,1,'初日研修あり'),('project-day-4-2','project-4','2026-06-19','10:00','18:00',5,1,''),('project-day-4-3','project-4','2026-06-20','09:00','17:00',6,2,'週末増員') on conflict (id) do nothing;
insert into public.availabilities (company_id,staff_id,work_date,status,note) values ('company-omega','staff-1','2026-06-14','available',''),('company-omega','staff-2','2026-06-14','available',''),('company-omega','staff-3','2026-06-16','available','') on conflict (staff_id,work_date) do update set status=excluded.status,note=excluded.note;

-- Development-only administrator. The password is stored in plain text temporarily.
-- Login ID: admin / password: omega1234
-- Before production use, replace this with a hashed password scheme.
insert into public.admin_accounts (id, company_id, login_id, password_text, name)
values ('admin-account-1', 'company-omega', 'admin', 'omega1234', '管理者')
on conflict (login_id) do update set password_text=excluded.password_text, name=excluded.name, company_id=excluded.company_id;
