'use client';

import { useEffect, useMemo, useState } from 'react';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { PageHeader } from '@/components/ui/PageHeader';
import { ResponsiveEditor } from '@/components/ui/ResponsiveEditor';
import { Select } from '@/components/ui/Select';
import { mockCompany, mockProjectTemplates, mockWorkplaces } from '@/lib/mockData';
import { getSupabaseBrowserClient } from '@/lib/supabaseClient';
import type { ProjectTemplate, Workplace } from '@/lib/types';

const STORAGE_KEY = 'omega-demo-project-templates';
const weekdays = ['日', '月', '火', '水', '木', '金', '土'];
const timeOptions = Array.from({ length: 30 }, (_, index) => {
  const totalMinutes = 7 * 60 + index * 30;
  return `${Math.floor(totalMinutes / 60).toString().padStart(2, '0')}:${(totalMinutes % 60).toString().padStart(2, '0')}`;
});
const makeTemplateId = () => `demo-template-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
const blankTemplate = (workplaceId: string): ProjectTemplate => ({ id: makeTemplateId(), company_id: mockCompany.id, workplace_id: workplaceId, template_name: '', title: '', start_time: '09:00', end_time: '17:00', location: '', required_people: 1, required_leaders: 1, note: '', weekdays: [1, 3, 5], created_at: new Date().toISOString() });
type EditorMode = 'create' | 'edit' | 'duplicate';

export default function Page() {
  const [items, setItems] = useState<ProjectTemplate[]>(mockProjectTemplates);
  const [workplaces, setWorkplaces] = useState<Workplace[]>(mockWorkplaces);
  const [q, setQ] = useState('');
  const [wp, setWp] = useState('all');
  const [editing, setEditing] = useState<ProjectTemplate | null>(null);
  const [mode, setMode] = useState<EditorMode>('edit');
  const [msg, setMsg] = useState('Supabaseなしでもテンプレートの作成/編集/削除/複製が画面上で反映されます');
  useEffect(() => { const saved = window.localStorage.getItem(STORAGE_KEY); if (saved) setItems(JSON.parse(saved) as ProjectTemplate[]); (async () => { const s = getSupabaseBrowserClient(); if (!s) return; const [{ data: templates }, { data: ws }] = await Promise.all([s.from('project_templates').select('*').order('created_at'), s.from('workplaces').select('*')]); if (templates?.length) setItems(templates as ProjectTemplate[]); if (ws?.length) setWorkplaces(ws as Workplace[]); setMsg('Supabaseと同期しています。未接続時は画面上のデモ操作として保存されます'); })(); }, []);
  useEffect(() => { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(items)); }, [items]);
  const filtered = useMemo(() => items.filter((t) => (wp === 'all' || t.workplace_id === wp) && `${t.template_name} ${t.title} ${t.location}`.toLowerCase().includes(q.toLowerCase())), [items, q, wp]);
  const locations = useMemo(() => Array.from(new Set(items.map((t) => t.location).filter(Boolean))).sort(), [items]);
  function create() { setEditing(blankTemplate(wp === 'all' ? workplaces[0]?.id ?? 'wp-1' : wp)); setMode('create'); }
  function edit(template: ProjectTemplate) { setEditing(template); setMode('edit'); }
  function duplicate(template: ProjectTemplate) { setEditing({ ...template, id: makeTemplateId(), template_name: `${template.template_name} のコピー`, created_at: new Date().toISOString() }); setMode('duplicate'); setMsg('複製フォームを開きました。内容を確認して保存してください。'); }
  async function save() { if (!editing) return; const normalized = { ...editing, template_name: editing.template_name.trim() || '無題テンプレート', title: editing.title.trim() || '無題の案件', location: editing.location.trim() || '未設定', required_people: Math.max(1, Number(editing.required_people) || 1), required_leaders: Math.max(0, Number(editing.required_leaders) || 0), weekdays: editing.weekdays.length ? editing.weekdays : [1] }; setItems((current) => current.some((x) => x.id === normalized.id) ? current.map((x) => x.id === normalized.id ? normalized : x) : [normalized, ...current]); const s = getSupabaseBrowserClient(); if (s) { const { error } = await s.from('project_templates').upsert(normalized); setMsg(error ? `${error.message}（画面上のみ更新しました）` : 'テンプレートを保存しました'); } else setMsg('Supabase未接続のため画面上のみ保存しました'); setEditing(null); }
  async function remove() { if (!editing || !confirm('このテンプレートを削除しますか？')) return; setItems((current) => current.filter((x) => x.id !== editing.id)); const s = getSupabaseBrowserClient(); if (s) await s.from('project_templates').delete().eq('id', editing.id); setMsg('テンプレートを削除しました'); setEditing(null); }
  return <div><PageHeader title="案件テンプレート" description="よくある案件を保存し、曜日指定で週/月の案件作成に使えます。" actions={<Button onClick={create} className="min-h-12 rounded-2xl">＋ 新規テンプレート</Button>} />{msg && <p className="mb-3 rounded-2xl bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-700">{msg}</p>}<div className="mb-5 grid gap-3 sm:grid-cols-[1fr_220px]"><Input placeholder="テンプレート名・案件名・場所で検索" value={q} onChange={(e) => setQ(e.target.value)} /><Select value={wp} onChange={(e) => setWp(e.target.value)}><option value="all">全事業所</option>{workplaces.map((w) => <option key={w.id} value={w.id}>{w.name}</option>)}</Select></div><Card className="hidden overflow-hidden p-0 lg:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">テンプレート</th><th className="px-4 py-3">事業所</th><th className="px-4 py-3">曜日</th><th className="px-4 py-3">時間</th><th className="px-4 py-3">必要</th><th className="px-4 py-3">操作</th></tr></thead><tbody>{filtered.map((t) => <tr key={t.id} onClick={() => edit(t)} className="cursor-pointer border-t border-slate-100 transition hover:bg-blue-50"><td className="px-4 py-3"><p className="font-bold text-slate-950">{t.template_name}</p><p className="text-xs text-slate-500">{t.title} · {t.location}</p></td><td className="px-4 py-3">{workplaces.find((w) => w.id === t.workplace_id)?.name ?? '事業所'}</td><td className="px-4 py-3">{formatWeekdays(t.weekdays)}</td><td className="px-4 py-3">{t.start_time}-{t.end_time}</td><td className="px-4 py-3">{t.required_people}名 / L{t.required_leaders ?? 0}名</td><td className="px-4 py-3"><Button variant="secondary" onClick={(e) => { e.stopPropagation(); duplicate(t); }}>複製</Button></td></tr>)}</tbody></table></Card><div className="mt-4 grid gap-4 lg:grid-cols-2">{filtered.map((t) => <TemplateCard key={t.id} template={t} workplace={workplaces.find((w) => w.id === t.workplace_id)?.name ?? '事業所'} onEdit={() => edit(t)} onDuplicate={() => duplicate(t)} />)}</div><ResponsiveEditor open={!!editing} title={mode === 'create' ? 'テンプレートを作成' : mode === 'duplicate' ? 'テンプレートを複製' : editing?.template_name ?? ''} subtitle="クリックしたカードを編集できます" onClose={() => setEditing(null)}>{editing && <TemplateForm template={editing} workplaces={workplaces} locations={locations} onChange={setEditing} onSave={save} onRemove={remove} showRemove={mode === 'edit'} />}</ResponsiveEditor></div>;
}
function TemplateCard({ template, workplace, onEdit, onDuplicate }: { template: ProjectTemplate; workplace: string; onEdit: () => void; onDuplicate: () => void }) { return <Card role="button" tabIndex={0} onClick={onEdit} onKeyDown={(e) => { if (e.key === 'Enter') onEdit(); }} className="cursor-pointer border-l-4 border-l-blue-600 p-4 transition hover:-translate-y-0.5 hover:shadow-md sm:p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-950">{template.template_name}</h2><p className="mt-1 text-sm text-slate-500">{workplace} · {template.location}</p></div><Badge tone="blue">{formatWeekdays(template.weekdays)}</Badge></div><p className="mt-3 font-semibold text-slate-800">{template.title}</p><div className="mt-4 grid grid-cols-3 gap-2 text-sm"><Info label="時間" value={`${template.start_time}-${template.end_time}`} /><Info label="必要人数" value={`${template.required_people}名`} /><Info label="必要L" value={`${template.required_leaders ?? 0}名`} /></div>{template.note && <p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm text-slate-600">{template.note}</p>}<div className="mt-4"><Button variant="secondary" onClick={(e) => { e.stopPropagation(); onDuplicate(); }}>複製</Button></div></Card>; }
function TemplateForm({ template, workplaces, locations, onChange, onSave, onRemove, showRemove }: { template: ProjectTemplate; workplaces: Workplace[]; locations: string[]; onChange: (template: ProjectTemplate) => void; onSave: () => void; onRemove: () => void; showRemove: boolean }) { return <div className="space-y-4"><datalist id="template-location-options">{locations.map((location) => <option key={location} value={location} />)}</datalist><Label text="テンプレート名"><Input value={template.template_name} onChange={(e) => onChange({ ...template, template_name: e.target.value })} placeholder="例：毎週 月水金 倉庫" /></Label><Label text="事業所"><Select value={template.workplace_id} onChange={(e) => onChange({ ...template, workplace_id: e.target.value })}>{workplaces.map((w) => <option key={w.id} value={w.id}>{w.name}</option>)}</Select></Label><Label text="案件名"><Input value={template.title} onChange={(e) => onChange({ ...template, title: e.target.value })} /></Label><div className="grid grid-cols-2 gap-3"><Label text="開始時間"><TimeSelect value={template.start_time} onChange={(value) => onChange({ ...template, start_time: value })} /></Label><Label text="終了時間"><TimeSelect value={template.end_time} onChange={(value) => onChange({ ...template, end_time: value })} /></Label></div><Label text="勤務場所"><Input list="template-location-options" value={template.location} onChange={(e) => onChange({ ...template, location: e.target.value })} /></Label><div className="grid grid-cols-2 gap-3"><Label text="必要人数"><Input type="number" min={1} value={template.required_people} onChange={(e) => onChange({ ...template, required_people: Number(e.target.value) })} /></Label><Label text="必要リーダー人数"><Input type="number" min={0} value={template.required_leaders ?? 0} onChange={(e) => onChange({ ...template, required_leaders: Number(e.target.value) })} /></Label></div><Label text="曜日指定"><WeekdayPicker value={template.weekdays} onChange={(weekdays) => onChange({ ...template, weekdays })} /></Label><Label text="備考"><textarea className="min-h-24 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100" value={template.note} onChange={(e) => onChange({ ...template, note: e.target.value })} /></Label><div className={`grid gap-3 ${showRemove ? 'grid-cols-2' : 'grid-cols-1'}`}><Button onClick={onSave}>保存</Button>{showRemove && <Button variant="danger" onClick={onRemove}>削除</Button>}</div></div>; }
function WeekdayPicker({ value, onChange }: { value: number[]; onChange: (value: number[]) => void }) { return <div className="grid grid-cols-7 gap-2">{weekdays.map((day, index) => <button key={day} type="button" onClick={() => onChange(value.includes(index) ? value.filter((v) => v !== index) : [...value, index].sort())} className={`rounded-xl px-2 py-3 text-sm font-bold ${value.includes(index) ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-600'}`}>{day}</button>)}</div>; }
function TimeSelect({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <Select value={value} onChange={(e) => onChange(e.target.value)}>{timeOptions.map((time) => <option key={time} value={time}>{time}</option>)}</Select>; }
function formatWeekdays(value: number[]) { return value.map((day) => weekdays[day]).join('・') || '未指定'; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-semibold text-slate-400">{label}</p><p className="mt-1 font-bold text-slate-900">{value}</p></div>; }
function Label({ text, children }: { text: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1 block text-sm font-bold text-slate-700">{text}</span>{children}</label>; }
