import { autoAssign } from '@/lib/autoAssign';
import { getDemoAssignments } from '@/lib/demo';
import { mockAvailabilities, mockProfiles, mockProjects } from '@/lib/mockData';
import type { Assignment, AssignmentResult } from '@/lib/types';
import { getClient, getCompanyId, demoAdminId } from './client';
export async function listAssignments(): Promise<Assignment[]> { const s=getClient(); if(!s) return getDemoAssignments(); const {data,error}=await s.from('assignments').select('*'); if(error) throw error; return (data?.length?data:getDemoAssignments()) as Assignment[]; }
export async function runAndSaveAutoAssign(): Promise<AssignmentResult[]> { const s=getClient(); if(!s) return autoAssign({companyId: await getCompanyId(), executedBy: demoAdminId, projects:mockProjects, profiles:mockProfiles, availabilities:mockAvailabilities, previousAssignments:getDemoAssignments()}); const companyId=await getCompanyId(); const [{data:projects},{data:profiles},{data:avs},{data:prev}] = await Promise.all([s.from('projects').select('*'),s.from('profiles').select('*'),s.from('availabilities').select('*'),s.from('assignments').select('*')]); const {data:run,error:runError}=await s.from('assignment_runs').insert({company_id:companyId, executed_by: (profiles?.find(p=>p.role==='admin')?.id ?? profiles?.[0]?.id ?? demoAdminId)}).select('*').single(); if(runError) throw runError; const results=autoAssign({companyId, executedBy: run.executed_by, projects:projects??[], profiles:profiles??[], availabilities:avs??[], previousAssignments:prev??[], runId:run.id}); const rows=results.flatMap(r=>r.assignments); if(rows.length){ const {error}=await s.from('assignments').insert(rows); if(error) throw error; } return results; }
export async function saveAssignment(row: Assignment): Promise<Assignment> { const s=getClient(); if(!s) return row; const {data,error}=await s.from('assignments').upsert(row).select('*').single(); if(error) throw error; return data as Assignment; }
export async function deleteAssignment(id:string){ const s=getClient(); if(!s) return; const {error}=await s.from('assignments').delete().eq('id',id); if(error) throw error; }
export async function confirmAssignments(projectId?: string){ const s=getClient(); if(!s) return; let q=s.from('assignments').update({status:'confirmed'}); if(projectId) q=q.eq('project_id',projectId); const {error}=await q; if(error) throw error; }
