import { mockAvailabilities, mockAvailabilityPeriods } from '@/lib/mockData';
import type { Availability, AvailabilityPeriod } from '@/lib/types';
import { getClient, getCompanyId } from './client';
export async function listAvailabilities(staffId?: string): Promise<Availability[]> { const s=getClient(); if(!s) return staffId?mockAvailabilities.filter(a=>a.staff_id===staffId):mockAvailabilities; let q=s.from('availabilities').select('*'); if(staffId) q=q.eq('staff_id',staffId); const {data,error}=await q; if(error) throw error; return (data?.length?data:(staffId?mockAvailabilities.filter(a=>a.staff_id===staffId):mockAvailabilities)) as Availability[]; }
export async function upsertAvailabilities(rows: Omit<Availability,'id'|'created_at'>[] | Availability[]) { const s=getClient(); if(!s) return rows as Availability[]; const company_id=await getCompanyId(); const {data,error}=await s.from('availabilities').upsert(rows.map(r=>({...r, company_id:r.company_id||company_id})), { onConflict:'staff_id,work_date' }).select('*'); if(error) throw error; return data as Availability[]; }
export async function listAvailabilityPeriods(): Promise<AvailabilityPeriod[]> { const s=getClient(); if(!s) return mockAvailabilityPeriods; const {data,error}=await s.from('availability_periods').select('*').order('created_at'); if(error) throw error; return (data?.length?data:mockAvailabilityPeriods) as AvailabilityPeriod[]; }

export async function saveAvailabilityPeriod(row: Omit<AvailabilityPeriod,'id'|'created_at'> & { id?: string }) { const s=getClient(); if(!s) return { ...row, id: row.id ?? `local-${row.period_type}-${Date.now()}`, created_at: new Date().toISOString() } as AvailabilityPeriod; const company_id=await getCompanyId(); const payload={...row, company_id:row.company_id||company_id}; const {data,error}=await s.from('availability_periods').upsert(payload).select('*').single(); if(error) throw error; return data as AvailabilityPeriod; }
export async function closeAvailabilityPeriods(type: AvailabilityPeriod['period_type'], exceptId?: string) { const s=getClient(); if(!s) return; let q=s.from('availability_periods').update({status:'closed'}).eq('period_type',type).eq('status','open'); if(exceptId) q=q.neq('id',exceptId); const {error}=await q; if(error) throw error; }
